apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: medical-demo
  labels:
    name: medical-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: medical-demo
    spec:
      containers:
      - name: medical-demo
        image: local/c7-systemd-httpd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: apache-data
        emptyDir: {}
